power_data <- read.table("/Users/hhvandi/Desktop/Coursera Data Science Specialization/Exploratory Data Analysis/Course Project /1/exdata-data-household_power_consumption/household_power_consumption.txt", sep = ";",stringsAsFactors=FALSE, header = TRUE)
head(power_data)
power_data$Date <- as.Date(power_data$Date, format = "%d/%m/%Y")
power <- power_data[(power_data$Date == "2007-02-01")| (power_data$Date == "2007-02-02"),]
power <- transform(power, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
power$Global_active_power <- as.numeric(as.character(power$Global_active_power))
power$Sub_metering_1 <- as.numeric(as.character(power$Sub_metering_1))
power$Sub_metering_2 <- as.numeric(as.character(power$Sub_metering_2))
power$Sub_metering_3 <- as.numeric(as.character(power$Sub_metering_3))
voltage <- as.numeric(power$Voltage)
png("plot4.png", width=480, height=480)
par(mfrow = c(2,2))
plot(power$timestamp, power$Global_active_power, type="l", xlab="", ylab= "Global Active Power", cex=0.2)
plot(power$timestamp, power$Voltage, type="l", xlab= "datetime", ylab= "Voltage")
plot(power$timestamp, power$Sub_metering_1, type="l", xlab="", ylab= "Energy sub metering")
lines(power$timestamp, power$Sub_metering_2, col="red")
lines(power$timestamp, power$Sub_metering_3, col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1), lwd=2.5, bty="0", col=c("black", "red", "blue"))
plot(power$timestamp, power$Global_reactive_power, type="l", xlab= "datetime", ylab= "Global_reactive_power")
dev.off()